apiVersion: v1
kind: Secret
metadata:
  name: rancher-scaler-once-secret
data:
  CATTLE_SECRET_KEY: {{ .Values.secret.CATTLE_SECRET_KEY }}
  RANCHER_BASE_URL:  {{ .Values.secret.RANCHER_BASE_URL }}
  SLACK_WEBHOOK_URL: {{ .Values.secret.SLACK_WEBHOOK_URL }}
type: Opaque
