apiVersion: batch/v1
kind: Job
metadata:
  name: rancher-scaler-once
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/controlplane: "true"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/controlplane
          value: "true"
          operator: Equal
        - effect: NoExecute
          key: node-role.kubernetes.io/etcd
          value: "true"
          operator: Equal
      containers:
        - name: rancher-scaler-once
          image: mojaloop/rancher-scaler:latest
          command: ["sh", "-c", "npm run {{ .Values.job.npmCommand }}"]
          volumeMounts:
            - name: config-volume
              mountPath: /opt/rancher-scaler/config
          env:
            - name: CATTLE_ACCESS_KEY
              value: {{ .Values.job.env.CATTLE_ACCESS_KEY }}
            - name: CATTLE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rancher-scaler-once-secret
                  key: CATTLE_SECRET_KEY
            - name: LOG_LEVEL
              value: {{ .Values.job.env.LOG_LEVEL }}
            - name: RANCHER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: rancher-scaler-once-secret
                  key: RANCHER_BASE_URL
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: rancher-scaler-once-secret
                  key: SLACK_WEBHOOK_URL
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: rancher-scaler-config-configmap
            items:
            - key: config_js
              path: rancher-scaler.config.js


