version: "3.7"

services:
  rancher-scale:
    build:
      context: .
    container_name: rancher-scaler
    volumes:
       - ./config/:/opt/rancher-scaler/config/
    environment:
      # Can be VERIFY, SCALE
      - METHOD=VERIFY
      # Can be UP or DOWN: required when METHOD=scale
      - SCALE=DOWN
      - PATH_TO_CONFIG=/opt/rancher-scaler/config/rancher-scaler.config.js
    env_file:
      - .env.docker