version: "3.7"

services:
  rancher-scale:
    build:
      context: .
    container_name: rancher-scaler
    volumes:
       - ./config/rancher-scaler.config.js:/opt/rancher-scaler/config/rancher-scaler.config.js
      #  TMP testing only
       - ./src/:/opt/rancher-scaler/src/
    environment:
      - SCALE=DOWN
    env_file:
      - .env.docker