version: "3.7"

services:
  rancher-scale:
    build:
      context: .
    container_name: rancher-scaler
    volumes:
       - ./config/:/opt/rancher-scaler/config/
      #  TMP testing only
       - ./src/:/opt/rancher-scaler/src/
    environment:
      - SCALE=DOWN
      - PATH_TO_CONFIG=/opt/rancher-scaler/config/rancher-scaler.config.js
    env_file:
      - .env.docker
    # command: 'sh -c "tail -f /dev/null"'