export enum ActionEnum {
  CLOUDWATCH_ADD_NODES = 'CLOUDWATCH_ADD_NODES',
  CLOUDWATCH_REMOVE_NODES = 'CLOUDWATCH_REMOVE_NODES',
  RUN_STARTUP_SCRIPT = 'RUN_STARTUP_SCRIPT',
  SLACK_NOTIFICATION = 'SLACK_NOTIFICATION',
  SLEEP = 'SLEEP',
}
