scaleDown:
  enabled: true
  # once an hour, at the start of the hour
  schedule: "1 * * * *"
  # Timeout after 30 minutes
  jobTimeout: 1800
  # Docker container runtime
  image: mojaloop/rancher-scaler:latest
  command: ["sh", "-c", "npm run scale:down"]

  # Container variables
  logLevel: debug
  cattleAccessKey: token-czddw

scaleUp:
  enabled: true
  # once an hour, 31 minutes past the hour
  schedule: "31 * * * *"
  # Timeout after 30 minutes
  jobTimeout: 1800

  # Docker container runtime
  image: mojaloop/rancher-scaler:latest
  command: ["sh", "-c", "npm run scale:up"]

  # Container variables
  logLevel: debug
  cattleAccessKey: token-czddw
